# Generated by Django 5.2.11 on 2026-02-24 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('course_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('DISABLED', 'Disabled')], db_index=True, default='VALID', max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='certificates/qr/')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('issuer_name', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='templates/backgrounds/')),
                ('dynamic_fields', models.JSONField(default=list, help_text='List of field maps. Example: [{name, x, y, font_size}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_uuid', models.UUIDField(db_index=True)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(db_index=True, default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
