# Generated by Django 5.2.11 on 2026-02-24 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['name'], name='certificate_name_ca152c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['is_active'], name='certificate_is_acti_4f5823_idx'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='certificates.certificate'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['recipient_name'], name='certificate_recipie_267001_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course_name'], name='certificate_course__e1da50_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issue_date'], name='certificate_issue_d_e50978_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['id', 'status', 'is_enabled'], name='certificate_id_8f4347_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['certificate_uuid', 'checked_at'], name='certificate_certifi_e8cabc_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['is_valid', 'checked_at'], name='certificate_is_vali_18590a_idx'),
        ),
    ]
