# Generated by Django 5.2.11 on 2026-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='jpg_file',
            field=models.FileField(blank=True, upload_to='certificates/images/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='png_file',
            field=models.FileField(blank=True, upload_to='certificates/images/'),
        ),
    ]
