# Generated by Django 5.2.11 on 2026-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificateoverlayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
