# Generated by Django 5.2.11 on 2026-04-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificatetemplate_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description of this template.'),
        ),
    ]
