# Generated by Django 5.2.11 on 2026-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificatetemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlog',
            name='source',
            field=models.CharField(choices=[('search', 'Search Form'), ('qr_scan', 'QR Scan Link'), ('api', 'External API'), ('admin', 'Admin Preview')], db_index=True, default='search', max_length=20),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['source', 'checked_at'], name='certificate_source_b31254_idx'),
        ),
    ]
